names:
- Bus
- Bike
- Car
- Pedestrian
- Truck
nc: 5
train: /mnt/nas2/users/shkim/work/projects/datasets/FishEyeChallenge/FishEye8K/train/images
val: /mnt/nas2/users/shkim/work/projects/datasets/FishEyeChallenge/FishEye8K/val/images
val_json: /mnt/nas2/users/shkim/work/projects/datasets/FishEyeChallenge/FishEye8K/val/val.json